---
title: "PSTAT131 Final Project"
author: "Joseph Chang, Tom Wei, Akul Bajaj"
date: "3/11/2022"
output: pdf_document
---

```{r setup, include=FALSE, echo = FALSE}
# set global chunk options: images will be 7x5 inches
knitr::opts_chunk$set(fig.width=7, fig.height=5, echo =TRUE)
options(digits = 4)
```

## packages

```{r}
#install.packages("tidyverse")
library(tidyverse)
library(knitr)
library(dplyr)
library(tidyverse)
library(modelr)
library(pander)
```

## read data
```{r}
# this is where we will input the data 

# first data 
labels <- c('Player','Position', 'Age', 'Team', 'Games', 'Minutes played', 'Player Efficiency Rating', 'true shooting percentage', '3-point attempt rate', 'free-throw attempt rate', 'offensive rebound percentage', 'defensive rebound percentage', 'total rebound percentage', 'assist percentage', 'steal percentage', 'block percentage', 'turnover percentage', 'usage rate', 'offensive win shares', 'defensive win shares', 'win shares','win shares per 48 minutes', 'Offensive Box Plus/Minus', 'Defensive Box Plus/Minus','Box Plus/Minus','Value Over Replacement')

bball_data_advanced <- read.csv("nba2021_advanced.csv", col.names = labels, na= "XXX")
bball_data_advanced



# second data
bball_data_txt <- read.delim("NBA_stats.txt")
bball_data_txt <- read.table("NBA_stats.txt", col.names = c('Rank','Player','Position','Age','Team', 'Games','Games Started', 'Minutes Played', 'field goals', 'field goal attempted', 'field goal percentage', '3-point field goals', '3-point field goals attempted', '3-point percentage', '2-field goals', '2-point field goals attempted', '2-point percentage', 'effective field goal percentage', 'free throws', 'free throws attempted', 'free throw percentage', 'offensive rebounds', 'defensive rebounds','total rebounds', 'assists', 'steals','blocks','turnovers','fouls','Points per game'), na = "XXX")
data.frame(bball_data_txt)

str(bball_data_txt)
glimpse(bball_data_txt)


# another data
X2020_2021_NBA_Stats_Player_Box_Score_Advanced_Metrics
mydf <- as.data.frame(X2020_2021_NBA_Stats_Player_Box_Score_Advanced_Metrics)
my_colnames <- c('Rank', 'Player', 'Team', 'Position', 'Age', 'Games Played', 'MPG', 'Minutes%', 'Usage Rate' , 'Turnover rate', 'free throws attempted', 'free throw percentage', '2-point field goals attempted', '2-point percentage', '3-point field goals attempted', 'three-point percentage', 'effective shooting percentage' , 'True shooting percentage', 'PPG', 'RPG', 'Total rebound percentage', 'APG', 'Assist percentage', 'SPG' ,'BPG', 'TPG', 'Versatility Index', 'Offensive Rating' , 'Defensive rating')
colnames(mydf) <- my_colnames
bball <- mydf[-1,-1]
  


# third data
# INCORRECT STATISTICS!! This only shows only 2021 (Jan to May?)
bball_data_per_game <- read.csv("nba2021_per_game.csv", col.names =c('Player','Position', 'Age', 'Team', 'Games', 'Games Started', 'Minutes played', 'field goals', 'field goal attempted', 'field goal percentage', '3-point field goals', '3-point field goals attempted', 'three-point percentage', '2-field goals', '2-point field goals attempted', '2-point percentage', 'effective field goal percentage', 'free throws', 'free throws attempted', 'free throw percentage', 'offensive rebounds', 'defensive rebounds','total rebounds', 'assists', 'steals','blocks','turnovers' , 'fouls','points per game'), na= "XXX")
bball_data_per_game

```

## Merge data?
```{r}
# this is where we merge data
ans <- merge(bball, bball_data_advanced, by ='Player')
subset(ans, select= -c(4,5))

```

## filter data
```{r}
# this is where we filter data by certain statistics

# filter players with usage rate over 30% and minutes played over 200 along with other of their main statistics
points_per_game_only <- bball_data_advanced %>% filter(usage.rate > 30, Minutes.played > 200) %>% select(Player, Age, Minutes.played:true.shooting.percentage, usage.rate, win.shares:Value.Over.Replacement)
points_per_game_only

# filter by keeping only certain predictors
# using the first data (bball_data_advanced)
wanted_predictors <- bball_data_advanced %>% select(Player, Age, Minutes.played:true.shooting.percentage, usage.rate, win.shares:Value.Over.Replacement)
wanted_predictors
```

## Correlation
```{r}
# correlation to see  vs 
my_cor <- bball_data_advanced %>% select(-c(Player, Position, Team)) %>% cor() %>% round(5) 
my_cor[(abs(my_cor) > 0.8)] 
```
## Plot
```{r}
plot()
```


## Linear regression?
```{r}
fit <- lm(Minutes.played ~ ., data = bball_data_advanced)
summary(fit)
```


## training and testing data
```{r}
# Set random seed
set.seed(3112022)

# Sample 70% observations as training data
train = sample(1:nrow(seats), 648*0.7)
seats.train = seats[train,]

# The rest 50% as test data
seats.test = seats[-train,]
```









